// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_z8ap-_wNXBJj7HLbGZ3Fw3f_kolrsug',
    appId: '1:265305195498:android:ce3276b884a1b225ad6893',
    messagingSenderId: '265305195498',
    projectId: 'tourmate-e22dd',
    databaseURL: 'https://tourmate-e22dd.firebaseio.com',
    storageBucket: 'tourmate-e22dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-S5-NxXZnFKf8SAVOCYtN8OKG_iXMhU',
    appId: '1:265305195498:ios:ab5e3574c85ae367ad6893',
    messagingSenderId: '265305195498',
    projectId: 'tourmate-e22dd',
    databaseURL: 'https://tourmate-e22dd.firebaseio.com',
    storageBucket: 'tourmate-e22dd.firebasestorage.app',
    androidClientId: '265305195498-i3uuj3uuhdg73tp31rqutv4sbfgnr3sj.apps.googleusercontent.com',
    iosClientId: '265305195498-jj4adeieenncb2ns4lomj97k95nc5dhi.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.menu',
  );
}
